---
#driver:
#  name: docker
#  binary: /usr/bin/docker
#  use_sudo: false
#  require_chef_omnibus: true
driver:
  name: dokken
  privileged: true # adds support for running systemd
  dns: ['192.168.104.102']
  
provisioner:
  name: dokken
  environments_path: environments
  roles_path: roles

transport:
  name: dokken
  #name: ssh
  #username: kitchen

platforms:
  - name: centos-7.2
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd

verifier:
  name: inspec
  root_path: '/opt/verifier'  
  profiles_path: test/integration/profiles  
  sudo: false
  format: progress

suites:
  - name: env-centos
    run_list:
      - recipe[sscep::default]
      - recipe[sscep-tests::default]
#      - recipe[export-node] # needed by integration tests    
